version: 2

# One PR for all ecosystems using multi-ecosystem groups
multi-ecosystem-groups:
  all-deps:
    schedule:
      interval: daily
      time: "06:00"
      timezone: Europe/London

updates:
  - package-ecosystem: "bundler"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "all-deps"
    open-pull-requests-limit: 1

  - package-ecosystem: "npm"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "all-deps"
    open-pull-requests-limit: 1

  - package-ecosystem: "github-actions"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "all-deps"
    open-pull-requests-limit: 1
